### PR TITLE
wkb: add benchmarking script

### PR DESCRIPTION
**Pull request by missinglink**
as mentioned in https://github.com/peterstace/simplefeatures/pull/421, this PR adds the benchmarking script used to generate the diffs shown on that PR description.

I'm opening this as a DRAFT since I'm not happy with the current state of this and would like some feedback about how to make it better before opening it up for merging:
- the test fixtures are a copy->paste of the ones from `wkb_test.go`, how best to share these?
- the `decode` function is a copy of `hexStringToBytes` with the `t *testing.T` removed

I tried a few things but none felt quite right:
- create a `wkb_util_test.go` file which has the hex decoder and the PostGIS/Spatialite fixtures in it
- create a `testdata/xxx` file which could be shared.

What do you think? what's the best way to share these between the `wkb_test.go` and `wkb_bench_test.go` files?

Usage:

```bash
go test -bench=. -count=5 -test.run=none -benchmem geom/wkb_bench_test.go > master.bench

# switch branch
go test -bench=. -count=5 -test.run=none -benchmem geom/wkb_bench_test.go > pr.bench

# note the count=5 above, the benchstat command requires each file 
# contains the concatenated output of several runs.
benchstat master.bench pr.bench
```

### CODE REVIEW

**Comment by missinglink** [comment]
Hi @peterstace sorry for the long delay, this should be good to go now.

I wasn't able to figure out a nice way of getting the call to `hexStringToBytes()` outside the benchmark codepath, although I'm not super concerned as it will be equal between runs.

One solution would be to add a `[]byte` field to `wkbWKTPair`, let me know if you'd like to go down that route.

**Comment by missinglink** [comment]
In regards to code organization, are you happy with this `geom/wkb_bench_test.go` file or would you prefer to move the `BenchmarkWKBParse` into `geom/wkb_test.go`?

I know some people prefer to have their benchmarks separated from the unit tests, while others prefer to keep them together, I'm happy to follow whatever convention you prefer.

**Comment by peterstace** [comment]
> although I'm not super concerned as it will be equal between runs.

Agreed, I'm not concerned either. Any differences in the benchmarked functionality would still show through as changes since the overhead would be unchanged.

> In regards to code organization, are you happy with this

I'm happy with how it is -- _most_ of the benchmarks are in separate files to regular unit tests, so that fits in well with what you've done.

**Review by peterstace — APPROVED** [review]
Thanks for the contribution!

**Pull request merged**
